nfl/react-wildcat

example/package.json, example/system.config.js, packages/react-wildcat-handoff/package.json, packages/react-wildcat-prefetch/package.json, packages/react-wildcat-prefetch/system.config.js
Test Plan:
Expected:
- All tests should pass.
=> Upgrade React Router to 1.0.0-rc4

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js
Test Plan:
Expected:
- All tests should pass.
=> Add support for more than one subdomain.

example/wildcat.config.js, package.json, packages/react-wildcat-handoff/src/simple.js, packages/react-wildcat-handoff/src/utils/defaultTemplate.js, packages/react-wildcat-handoff/src/utils/simpleRender.js, packages/react-wildcat-handoff/test/simpleHandoffSpec.js, packages/react-wildcat/src/middleware/renderReactWithJSPM.js
This adds a simple render option that bypasses most of the heavy server-side rendering. Instead it does minimal work and returns a shell HTML payload.
=> Add a bare bones simple renderer

packages/react-wildcat-handoff/src/utils/defaultTemplate.js
Add missing escape in regex pattern
=> fix(react-wildcat-handoff): escape regex character

packages/react-wildcat-prefetch/src/index.js, packages/react-wildcat-prefetch/src/test/browser/fixtures/stubData.js, packages/react-wildcat-prefetch/src/test/browser/prefetchSpec.js
Allow multiple prefetch calls to be made.
=> fix(react-wildcat-prefetch): fix prefetch hydration

packages/react-wildcat-prefetch/src/test/browser/fixtures/stubData.js, packages/react-wildcat-prefetch/src/test/browser/prefetchSpec.js
add tests for prefetching multiple components
=> test(react-wildcat-prefetch): add missing tests

packages/react-wildcat-prefetch/src/index.js, packages/react-wildcat-prefetch/src/test/browser/fixtures/stubData.js, packages/react-wildcat-prefetch/src/test/browser/prefetchSpec.js
Made one change and added 2 tests. Before the update, only array hydration passed, now hydration and rehydration both pass.
=> Bugfix: array handling

packages/react-wildcat/cli/utils/handle.js, packages/react-wildcat/cli/utils/handleFile.js, packages/react-wildcat/cli/utils/wildcatBabelWorker.js, packages/react-wildcat/cli/utils/write.js, packages/react-wildcat/cli/wildcatBabel.js
Speed up the Babel transpiler by spawning multiple workers across available CPUs.
=> perf(react-wildcat): Transpile code over multiple workers

packages/react-wildcat-handoff/src/utils/defaultTemplate.js, packages/react-wildcat-prefetch/src/test/browser/fixtures/defaultTemplate.js, packages/react-wildcat/src/middleware/renderReactWithJspm.js, packages/react-wildcat/src/utils/blueBoxOfDeath.js, packages/react-wildcat/test/appServerSpec.js
=> fix(react-wildcat): Display stack traces if available

packages/react-wildcat-handoff/src/utils/defaultTemplate.js
If enabled, all modules will be stored in IndexedDB
=> fix(react-wildcat-handoff): Cache all modules

packages/react-wildcat/src/server.js, packages/react-wildcat/src/staticServer.js, packages/react-wildcat/test/appServerSpec.js, packages/react-wildcat/test/staticServerSpec.js
Adding hooks for `onBeforeClusterStart` and `onWorkerStart`
=> fix(react-wildcat): Add more lifecycle hooks

packages/react-wildcat/cli/wildcat.js, packages/react-wildcat/cli/wildcatBabel.js, packages/react-wildcat/cli/wildcatStaticServer.js, packages/react-wildcat/src/middleware/renderReactWithJspm.js, packages/react-wildcat/src/server.js, packages/react-wildcat/src/utils/blueBoxOfDeath.js, packages/react-wildcat/src/utils/logger.js, packages/react-wildcat/test/appServerSpec.js
Updates `logger.error` to log both the error message and the stack trace (if available)
=> fix(react-wildcat): Add more verbose error logging

example/package.json, example/src/routes/HelmetExample/HelmetExample.js, example/system.config.js, package.json, packages/react-wildcat-handoff/package.json, system.config.js
Upgrade React Helmet in handoff and example projects
=> chore(handoff): Upgrade React Helmet

packages/react-wildcat/cli/test/utils/handleSpec.js, packages/react-wildcat/cli/test/utils/prepImportableModuleSpec.js, packages/react-wildcat/cli/test/utils/prepTranspiledModuleSpec.js, packages/react-wildcat/cli/test/wildcatBabelSpec.js, packages/react-wildcat/cli/utils/handle.js, packages/react-wildcat/cli/utils/handleFile.js, packages/react-wildcat/cli/utils/prepImportableModule.js, packages/react-wildcat/cli/utils/prepTranspiledModule.js, packages/react-wildcat/cli/utils/transpiler.js, packages/react-wildcat/src/middleware/babelDevTranspiler.js, packages/react-wildcat/src/utils/createTranspiledModule.js, packages/react-wildcat/test/staticServerSpec.js, packages/react-wildcat/test/utils/createTranspiledModuleSpec.js
Renaming some utility files for clarity
=> Descriptive file names

packages/react-wildcat/cli/utils/prepTranspiledModule.js, packages/react-wildcat/cli/wildcat.js, packages/react-wildcat/cli/wildcatBabel.js, packages/react-wildcat/cli/wildcatStaticServer.js
Change relative paths to package.json to be absolute
=> fix(react-wildcat): Absolute paths to package.json

packages/react-wildcat/src/utils/createImportableModule.js, packages/react-wildcat/src/utils/createTranspiledModule.js, packages/react-wildcat/src/utils/logCreateSuccess.js
=> fix(react-wildcat): Use relative path in CREATE log

example/package.json, example/src/components/Application/ApplicationContext.js, example/system.config.js, package.json, packages/react-wildcat-handoff/package.json, packages/react-wildcat-handoff/src/client.js, packages/react-wildcat-handoff/src/server.js, packages/react-wildcat-handoff/src/utils/clientContext.js, packages/react-wildcat-handoff/src/utils/clientRender.js, packages/react-wildcat-handoff/src/utils/getDomainRoutes.js, packages/react-wildcat-handoff/src/utils/serverContext.js, packages/react-wildcat-handoff/src/utils/serverRender.js, packages/react-wildcat-handoff/test/stubFixtures.js, system.config.js
Adding headers for cookie and referrer data
=> fix(react-wildcat-handoff): Add missing headers

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js, packages/react-wildcat-handoff/test/serverHandoffSpec.js, packages/react-wildcat-handoff/test/stubFixtures.js
=> ADD: Ability to alias by subdomain

CHANGELOG.md, example/package.json, example/system.config.js, package.json, packages/react-wildcat-handoff/package.json, packages/react-wildcat-handoff/src/utils/defaultTemplate.js, packages/react-wildcat-handoff/src/utils/getDomainRoutes.js, packages/react-wildcat-handoff/test/serverHandoffSpec.js, packages/react-wildcat-handoff/test/stubFixtures.js, packages/react-wildcat-prefetch/src/test/browser/fixtures/defaultTemplate.js, system.config.js
This PR fixes an issue where Firefox must wait for the IndexedDB cache to be ready before interacting with it.
=> fix(react-wildcat-handoff): Fix initializing an IndexedDB cache in Firefox

packages/react-wildcat-handoff/src/utils/serverRender.js
De-reference the initialData object after the Promise is fulfilled
=> perf(react-wildcat-handoff): De-reference initialData object

CHANGELOG.md, example/package.json, example/system.config.js, package.json, packages/react-wildcat-handoff/package.json, packages/react-wildcat-handoff/src/utils/serverRender.js, packages/react-wildcat-prefetch/package.json, packages/react-wildcat-prefetch/src/index.js, packages/react-wildcat-prefetch/src/test/browser/prefetchSpec.js, packages/react-wildcat-prefetch/test/fixtures/stubData.js, packages/react-wildcat-prefetch/test/prefetchSpec.js, system.config.js
Fix a bug where the prefetched server data was being lost in transition
=> fix(react-wildcat-prefetch): Fix lost reference to prefetched data

.travis.yml
jspm link is causing builds to fail on travis when a PR is updated
=> Remove cache directories from travis

packages/react-wildcat-handoff/package.json, packages/react-wildcat-handoff/src/utils/getDomainRoutes.js, packages/react-wildcat-handoff/test/serverHandoffSpec.js, packages/react-wildcat-handoff/test/stubFixtures.js
Resolve domain clobbering when multiple domain aliases are provided
=> fix(react-wildcat-handoff): Resolve domain clobbering

CHANGELOG.md, packages/react-wildcat-handoff/package.json
=> Custom 404 Error template support.

.dockerignore, Dockerfile, docker-compose.yml, packages/react-wildcat/test/staticServerSpec.js, shell/combine-coverage.sh
docker config updates and test fixes so we can run tests in docker
=> fix docker

example/package.json, example/yarn.lock, packages/react-wildcat-handoff/yarn.lock, packages/react-wildcat-prefetch/yarn.lock, packages/react-wildcat-test-runners/yarn.lock, packages/react-wildcat/package.json, packages/react-wildcat/src/staticServer.js, packages/react-wildcat/yarn.lock, yarn.lock
Running `npm run dev` in the `example` folder now works again
=> Fix example project

README.md
* small update to readme to add wildcat logo
=> Update Readme.md with real wildcat logo
