nfl/react-wildcat

packages/react-wildcat-prefetch/src/index.js

Incoming initial data can be a string / object / array, so let's remove this spread.
Test Plan:
Expected:
- All tests should pass

Remove object spread on initial data

---

example/src/routes/PrefetchExample/routes.js
packages/react-wildcat-handoff/src/client.js
packages/react-wildcat-handoff/src/utils/renderContext.js

Use the `match` helper to do some client-side route-matching, which supresses the delay between server and client rendering.
Test Plan:
Expected:
- All tests should pass

Suppress white flash between server / client render

---

packages/react-wildcat-handoff/.npmignore
packages/react-wildcat-handoff/src/utils/clientRender.js

This file gets rendered as-is on the client, but not all of our target browsers support arrow functions.

Convert arrow functions to es5

---

Makefile
example/wildcat.config.js
packages/react-wildcat/src/server.js
packages/react-wildcat/src/staticServer.js
shell/clean-example.sh
shell/clean.sh
shell/install-example.sh
shell/install.sh

- Make https optional
- Allow devs to set custom security options
- Decouple appServer / staticServer settings
- (e.g., you can now serve the app server using http and the static server using https)
- `cd example && npm run dev`
- Site should be available at [https://localhost:3000](https://localhost:3000)
- In `example/wildcat.config.js`, disable `http2`, enable `https`.
- Site should be available at [https://localhost:3000](https://localhost:3000)
- In `example/wildcat.config.js`, disable both `http2` and `https`.
- Site should be available at [http://localhost:3000](http://localhost:3000)

Make https optional

---

example/src/routes/ErrorExample/routes.js
example/src/routes/FlexboxExample/routes.js
example/src/routes/HelmetExample/routes.js
example/src/routes/IndexExample/routes.js
example/src/routes/PrefetchExample/routes.js
packages/react-wildcat-ensure/.npmignore
packages/react-wildcat-ensure/README.md
packages/react-wildcat-ensure/package.json
packages/react-wildcat-ensure/src/index.js
packages/react-wildcat-ensure/src/test/browser/ensureSpec.js
packages/react-wildcat-ensure/src/test/browser/fixtures/AsyncExampleOne.js
packages/react-wildcat-ensure/src/test/browser/fixtures/AsyncExampleTwo.js
packages/react-wildcat-ensure/src/test/browser/fixtures/routes.js
packages/react-wildcat-ensure/src/test/browser/fixtures/routesArray.js
packages/react-wildcat-ensure/src/test/browser/fixtures/routesHash.js
packages/react-wildcat-ensure/src/test/browser/fixtures/routesMissing.js
packages/react-wildcat-ensure/src/test/browser/fixtures/routesMissingArray.js
packages/react-wildcat-ensure/src/test/browser/fixtures/routesMissingHash.js
shell/install-example.sh
shell/install.sh

A wrapper for [`System.import`](https://github.com/systemjs/systemjs) that behaves like Webpack's [`require.ensure`](https://webpack.github.io/docs/code-splitting.html#require-ensure):
- initial import calls are asynchronous
- subsequent import calls returns a synchronous cached import response
Designed for compatibility with React Router's [asynchronous route loading](https://github.com/rackt/react-router/blob/master/docs/guides/advanced/DynamicRouting.md).
Importing a single module:
```js
import ensure from "react-wildcat-ensure";
// Lazy loaded component
export function getComponent(location, cb) {
ensure("./AsyncComponent.js", module, (err, module) => {
return cb(err, module);
});
}
```
Importing a key/value hash of modules:
```js
import ensure from "react-wildcat-ensure";
// Lazy …
```

react-wildcat-ensure

---

packages/react-wildcat-handoff/src/utils/serverRender.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js
packages/react-wildcat-handoff/test/stubFixtures.js
packages/react-wildcat/src/middleware/renderReactWithJSPM.js
packages/react-wildcat/src/utils/blueBoxOfDeath.js

This fix disables the check against the  header in development mode, and always
serves the server-side render from cache. This improves performance during development while devs
have browser cache disabled. The WebSocket file change listener still behaves as usual and will
still expire route caches when necessary, so devs will still see fresh data when necessary.

perf(react-wildcat): disable cache check in dev mode

---

packages/react-wildcat/src/middleware/renderReactWithJSPM.js
packages/react-wildcat/src/server.js
packages/react-wildcat/src/utils/connectToWebSocketServer.js
packages/react-wildcat/test/appServerSpec.js

Using Weak Maps to store cache data, which should perform faster than a basic object hash. (Source:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)

perf(react-wildcat): store cache data in a weak map

---

package.json
packages/react-wildcat-handoff/package.json
packages/react-wildcat-handoff/src/utils/serverRender.js

Workaround for the Material UI server-side navigator.userAgent requirement.

fix(react-wildcat-handoff): Add workaround for navigator.userAgent requirement

---

packages/react-wildcat-handoff/src/server.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js

Trigger a Promise rejection if an error is thrown.

fix(react-wildcat-handoff): reject Promise if error is found

---

example/wildcat.config.js
packages/react-wildcat-handoff/src/utils/defaultTemplate.js
packages/react-wildcat-handoff/test/stubFixtures.js
packages/react-wildcat-hot-reloader/package.json
packages/react-wildcat-hot-reloader/src/index.js
packages/react-wildcat/package.json
packages/react-wildcat/src/middleware/renderReactWithJspm.js
packages/react-wildcat/src/utils/customJspmLoader.js
packages/react-wildcat/src/utils/hotReloaderWebSocket.js
packages/react-wildcat/src/utils/templates/wildcat.config.js

This pull request allows devs to provide custom hot-reloading solutions. The default functionality uses WebSockets, but devs can now integrate with other reporting tools such as [Kafka](kafka.apache.org).

refactor(react-wildcat-hot-reloader): make hot reloading configurable

---

packages/react-wildcat/src/middleware/babelDevTranspiler.js
packages/react-wildcat/test/staticServerSpec.js

Don't wait for the transpiled result to write to disk. Instead, use the in-memory result as the server response.

perf(react-wildcat): improve initial server response

---

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js
packages/react-wildcat-handoff/test/stubFixtures.js

Support temporary subdomains. Useful for staging environments, i.e. using www-staging.example.com to
test the www subdomain, or staging-foo.example.com to test the foo subdomain, etc.

feat(react-wildcat-handoff): support for ephemeral subdomains

---

example/package.json
example/src/components/Application/Application.js
example/src/routes/PrefetchExample/PrefetchExample.js
example/src/test/e2e/objects/ErrorPageObject.js
example/src/test/e2e/objects/FlexboxPageObject.js
example/src/test/e2e/objects/HelmetPageObject.js
example/src/test/e2e/objects/IndexPageObject.js
example/src/test/e2e/objects/PrefetchPageObject.js
example/src/test/e2e/utils/contextStub.js
package.json
packages/react-wildcat-prefetch/src/test/browser/fixtures/HelloES7.js
packages/react-wildcat-prefetch/src/test/browser/prefetchSpec.js
packages/react-wildcat-test-runners/src/karma.js
packages/react-wildcat-test-runners/src/protractor.js
packages/react-wildcat/test/appServerSpec.js
packages/react-wildcat/test/staticServerSpec.js

Updated babel-eslint to 4.1.7 in order to fix build errors when a user runs `make install`

chore: Updated babel-eslint to 4.1.7

---

example/package.json
package.json

npm install is throwing an error, downgrading eslint prevents it from happening until https://github.com/eslint/eslint/issues/5476 is fixed

Downgraded eslint

---

example/api/sampleServerOnlyApi.js
example/package.json
example/wildcat.config.js
packages/react-wildcat/src/server.js
packages/react-wildcat/src/utils/templates/wildcat.config.js
packages/react-wildcat/test/appServerSpec.js

Thanks to the kick-start feedback in #68, here is an PR in attempt at adding a custom middleware hook for react-wildcat's server side...
Any suggestions/thoughts?

Custom middleware

---

packages/react-wildcat/src/utils/getWildcatConfig.js
packages/react-wildcat/test/getWildcatConfigSpec.js

`react-wildcat` should never override a value the developer specifies in `wildcat.config.js`.
I have 1 commit here
Trying to work through Heroku deployment. I got to the point where my whole site could be run through a single server.
The last problem was trying to get the template rendered to use my custom domain to render the root template with `http://mysite.herokuapp.com/jspm_packages/system.js`, however this always rendered with `http://localhost:12345/jspm_packages/system.js`. 
I tried updating the `wildcatConfig.serverSettings.staticServer.hostname/port` but each time I touched those values I only ever got `500` responses from heroku (with no error logs that I could find).
After digging in, I found out about the `staticUrl` and `originUrl` values. When I tried to hard-code them in …

Do not override my config

---

packages/react-wildcat/cli/wildcat.js
packages/react-wildcat/cli/wildcatStaticServer.js
packages/react-wildcat/src/middleware/babelDevTranspiler.js
packages/react-wildcat/src/middleware/renderReactWithJspm.js
packages/react-wildcat/src/staticServer.js
packages/react-wildcat/src/utils/customJspmLoader.js
packages/react-wildcat/src/utils/templates/wildcat.config.js
packages/react-wildcat/test/appServerSpec.js
packages/react-wildcat/test/staticServerSpec.js

Changes:
```
70c20b4
refactor(react-wildcat): Log uncaught exceptions instead of throwing them
7c723a6
perf(react-wildcat): Avoid multiple writes to disk when transpiling on the
server
Fix a race condition where the static server was writing to disk multiple
times on concurrent requests. Now the first request to transpile a file
will save its Promise to cache, and subsequent requests will first check if
that Promise is available in cache before requesting a transpilation.
1135a6b
perf(react-wildcat): Load jspm packages from the local file system in
development mode
```

Server performance improvements

---

packages/react-wildcat/src/server.js
packages/react-wildcat/src/staticServer.js
packages/react-wildcat/src/utils/templates/wildcat.config.js
packages/react-wildcat/test/appServerSpec.js
packages/react-wildcat/test/staticServerSpec.js

Adding onBeforeStart, onStart and onAfterStart lifecycle hooks to both the app and static servers. Useful for bootstrapping functionality before the server runs.

feat(react-wildcat): Add lifecycle hooks

---

CHANGELOG.md
example/package.json
packages/react-wildcat/cli/test/wildcatBabelSpec.js
packages/react-wildcat/cli/utils/copyFiles.js
packages/react-wildcat/package.json
packages/react-wildcat/src/middleware/babelDevTranspiler.js
packages/react-wildcat/src/utils/createImportableModule.js
packages/react-wildcat/test/staticServerSpec.js

Fix an issue where importable modules were exporting absolute paths to
binary files. Also adding tests to cover this output.

fix(react-wildcat): Fix exported paths to binary files.

---

packages/react-wildcat/cli/test/utils/handleSpec.js
packages/react-wildcat/cli/test/utils/prepImportableModuleSpec.js
packages/react-wildcat/cli/test/utils/prepTranspiledModuleSpec.js
packages/react-wildcat/cli/test/wildcatBabelSpec.js
packages/react-wildcat/cli/utils/handle.js
packages/react-wildcat/cli/utils/handleFile.js
packages/react-wildcat/cli/utils/prepImportableModule.js
packages/react-wildcat/cli/utils/prepTranspiledModule.js
packages/react-wildcat/src/middleware/babelDevTranspiler.js
packages/react-wildcat/src/utils/createTranspiledModule.js
packages/react-wildcat/test/staticServerSpec.js
packages/react-wildcat/test/utils/createTranspiledModuleSpec.js

Karma / Protractor expect full file paths to generate the correct source mapping.

fix(react-wildcat): Fix sourceFileName path

---

packages/react-wildcat/package.json

Bump ws@1.0.1m, a node.js websocket library

chore(react-wildcat): ws module upgrade

---

packages/react-wildcat/cli/wildcat.js
packages/react-wildcat/cli/wildcatBabel.js
packages/react-wildcat/cli/wildcatStaticServer.js

Make all paths in entry files absolute. Just in case.

fix(react-wildcat): More absolute paths to modules

---

Makefile
example/protractor.config.js
example/src/test/e2e/flows/indexPageFlow.js
example/src/test/e2e/flows/prefetchPageFlow.js
packages/react-wildcat/cli/test/wildcatBabelSpec.js
packages/react-wildcat/test/appServerSpec.js
packages/react-wildcat/test/staticServerSpec.js
packages/react-wildcat/test/utils/loggerSpec.js
shell/install-example.js

- Adds file extensions to tests and updates an issue where stubs were incorrectly applied
- Un-silence initial install commands
- Fix an issue where npm packages were incorrectly linked during example bootstrapping

Test/Setup Cleanup

---

packages/react-wildcat-prefetch/src/index.js

This will help code debugging by wrapping the original component's display name instead of overwriting it.

fix(react-wildcat-prefetch): Wrap composed component display name to avoid losing its canonical name

---

Makefile
example/protractor.config.js
example/src/test/e2e/flows/indexPageFlow.js
example/src/test/e2e/flows/prefetchPageFlow.js
packages/react-wildcat/cli/test/utils/handleFileSpec.js
packages/react-wildcat/cli/test/wildcatBabelSpec.js
packages/react-wildcat/cli/utils/handleFile.js
packages/react-wildcat/test/appServerSpec.js
packages/react-wildcat/test/staticServerSpec.js
packages/react-wildcat/test/utils/loggerSpec.js
shell/install-example.js

Fixes an issue where the logger functions were being lost when running this function in a worker
process.

fix(wildcat-babel): Reimport the logger utility in worker helper

---

packages/react-wildcat/package.json
packages/react-wildcat/src/server.js
packages/react-wildcat/src/utils/blueBoxOfDeath.js

Remove koa-favicon, users can now define their own custom middleware for minor fixes like this.

chore(react-wildcat): Remove koa-favicon

---

karma.config.js
packages/react-wildcat-handoff/src/utils/serverRender.js
packages/react-wildcat-prefetch/package.json
packages/react-wildcat-prefetch/src/index.js
packages/react-wildcat-prefetch/src/test/browser/fixtures/CustomPrefetchStatic.js
packages/react-wildcat-prefetch/src/test/browser/fixtures/DefaultPrefetchStatic.js
packages/react-wildcat-prefetch/src/test/browser/fixtures/stubData.js
packages/react-wildcat-prefetch/src/test/browser/prefetchSpec.js

Allow @prefetch to be invoked without arguments. Given a React component that assumes default values, it can now be wrapped with an arg-less decorator:
```js
@prefetch
class Foo extends React.Component {
// Prefetch assumes fetchData as the default prefetch handler
static fetchData() {
return Promise.resolve(42);
}
render() {
// this.props.asyncData will be populated with data from Foo.fetchData
const {asyncData} = this.props;
return <div>{asyncData}</div>; // Prints <div>42</div>
}
}
```

feat(react-wildcat-prefetch): Make decorator arguments optional

---

packages/react-wildcat/src/server.js
packages/react-wildcat/src/staticServer.js
packages/react-wildcat/src/utils/templates/wildcat.config.js

By default, only start one process per server in non-production mode. This value is configurable.

fix(react-wildcat): Limit to one worker per server in dev mode

---

package.json
packages/react-wildcat-handoff/src/utils/serverRender.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js
packages/react-wildcat-handoff/test/stubFixtures.js
packages/react-wildcat/src/utils/templates/wildcat.config.js

Add a configuration to use renderToString vs renderToStaticMarkup

feat(react-wildcat-handoff): Add configurable server render type

---

packages/react-wildcat-handoff/src/utils/serverRender.js

Default `__INITIAL_DATA__` value should be `null` when no data is prefetched

fix(react-wildcat-handoff): Fix default __INITIAL_DATA__ value

---

example/package.json
example/system.config.js
packages/react-wildcat-handoff/src/utils/defaultTemplate.js

Sharding vendors across multiple files. Improves bootstrap performance over 3G speeds.

perf(example): Move React into separate bundle.

---

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js

Add development-specific TLDs following this guide: https://iyware.com/dont-use-dev-for-development/
/cc @potench

fix(react-wildcat-handoff): Add development-specific TLDs

---

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js
packages/react-wildcat-handoff/test/stubFixtures.js

This PR adds support for domain aliases when using domain matching. It works by defining a `domainAliases` config in your domain config:
```js
{
domainAliases: {
example: [
localhost // Navigating to https://localhost:3000 will now match the example domain
]
},
example: {
www: {} // ...etc
}
}
```

feat(react-wildcat-handoff): Add support for domain aliases

---

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js

fix(react-wildcat-handoff): Replace arrow functions with named callbacks.

---

.travis.yml

There's been broken builds because of missing write access to cached node_module folders

Fix broken Travis builds

---

packages/react-wildcat-handoff/src/utils/getDomainRoutes.js
packages/react-wildcat-handoff/webpack.config.js

Adding `.dev` to customTlds and remove `parse-domain` from generated Webpack bundle.

fix(react-wildcat-handoff): Add dev to customTlds

---

shell/combine-coverage.sh

The original command was uploading both the lcov.info and coverage.json file. We only want lcov.info uploaded

build(wildcat): Specify a single code coverage file

---

packages/react-wildcat-handoff/package.json
packages/react-wildcat-handoff/src/utils/getDomainRoutes.js
packages/react-wildcat-handoff/test/stubFixtures.js

Fixes a bug to allow `x.example.com` to alias to `y.anotherdomain.com`

fix(react-wildcat-handoff): Handle subdomain aliases in getDomainRoutes

---

example/wildcat.config.js
packages/react-wildcat-handoff/src/utils/serverRender.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js
packages/react-wildcat-handoff/test/stubFixtures.js

Added optional wildcatConfig parameter for passing in custom 404 error template HTML to react-wildcat-handoff that will be rendered if a route is not found.

Feature: Custom 404 Error template support

---

CHANGELOG.md
packages/react-wildcat-handoff/src/utils/serverRender.js
packages/react-wildcat-handoff/test/stubFixtures.js

htmlNotFoundTemplate property in wildcat.config.js now expects a function that returns the html template string not a string

	fix(react-wildcat-handoff): htmlNotFoundTemplate

---

CHANGELOG.md
packages/react-wildcat-handoff/package.json
packages/react-wildcat-handoff/src/utils/serverRender.js
packages/react-wildcat-handoff/test/serverHandoffSpec.js
packages/react-wildcat-handoff/test/stubFixtures.js

A routerProps property, containing an object with a status property with a value of 404, can be
added to a component route that can be used to return an http 404 status code.

Feature not-found component support
